### ISSUE TITLE
Limit reached error comes back as result instead of err

### ISSUE THREAD

**Issue by ChiperSoft** [mktmpio/node-mktmpio#2]
If the account has reached its limit of database instances, the callback will fire without an error but instead with the following as the result:

```
{ error: 'Limit reached 1 of 1' }
```

This should be an Error object passed on the first argument of the callback.

**Comment by rmg** [comment]
Good catch, thanks for reporting :-)

**Comment by rmg** [comment]
@ChiperSoft fix published as [mktmpio@1.0.0-10](https://github.com/mktmpio/node-mktmpio/releases/tag/v1.0.0-10)
